spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASS:alstn124}
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher




host:
  client: "http://localhost:3000"